### ISSUE TITLE
Questions about the mod

### ISSUE THREAD

**Issue by asiekierka** [AlgorithmX2/Chisels-and-Bits-Localization#4]
I couldn't find a better means of communication (Minecraft Forums is *definitely* not better), so I apologize for being somewhat off-topic.

1. "No, You may link to the pages/files hosted on curse however." conflicts with "Yes [, you can use the mod in modpacks]" for any modpacks not hosted on Curse and not using MCUpdater. Can the mod, then, be re-hosted for the purposes of providing a modpack?

2. Feature request - an icon in the lower-right of a chisel signalizing the mode it's currently in.

**Comment by AlgorithmX2** [comment]
I'm not sure why you think the issue tracker on curse is not appropriate.

However,
1. I clarified the details about third party hosting, stating that its allowed for mod packs.

2. Added to Curse tracker, http://minecraft.curseforge.com/projects/chisels-bits/issues/1588

Not a bad idea, keeping track of the current mode isn't too hard with the outlines being registered, but there are cases where you can't see it properly, that might also be useful ( some way to see the affected area though the solid object. )

**Comment by asiekierka** [comment]
I did not realize Curse has an issue tracker.
